---
# vi: ts=2 sw=2 et:
# SPDX-License-Identifier: LGPL-2.1-or-later
#
name: Coverity

on:
  workflow_dispatch:
  schedule:
    # Run Coverity daily at midnight
    - cron:  '0 0 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.repository == 'janbrummer/libproxy2'
    env:
      # Set in repo settings -> secrets -> actions
      COVERITY_SCAN_TOKEN:              "${{ secrets.COVERITY_SCAN_TOKEN }}"
      COVERITY_SCAN_NOTIFICATION_EMAIL: "${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}"
    steps:
      - name: Repository checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Ubuntu Setup
        if: runner.os == 'Linux'
        run: |
          sudo apt install \
          libglib2.0-dev \
          libgirepository1.0-dev \
          duktape-dev \
          libsoup-3.0-dev \
          meson \
          gcovr \
          gi-docgen \
          libpeas-dev \
          gsettings-desktop-schemas-dev \
          libcurl4-openssl-dev
      - name: Build & upload the results
        run: .github/coverity.sh
